# Generated by Django 4.1.7 on 2023-03-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_earningreport_newsarticle_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.stock'),
        ),
        migrations.AlterField(
            model_name='earningreport',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.stock'),
        ),
    ]
